### ISSUE TITLE
failed to create state file when provided

### ISSUE THREAD

**Issue by VinozzZ** [getporter/operator#109]
I'm getting the following error when trying to use a porter bundle that has "state" provided in the manifest when running in the operator:
could not create a new gzip reader for the statefile: unexpected EOF
This is when using "state" to store off terraform tfstate files ex:
```yaml
state:
  - name: tfstate
    path: terraform/terraform.tfstate
  - name: tfvars
    path: terraform/terraform.tfvars.json
```
This works when setting the tfstate file as a bundle output and using it that way.
Running this on beta.2 in the operator

originally reported by @sgettys
