### ISSUE TITLE
PorterConfig CRD should use the same keys as defined in the porter config

### ISSUE THREAD

**Issue by sgettys** [getporter/operator#125]
The porter config yaml uses kebab-case for the config keys but the PorterConfig CRD has these fields defined as camelCase. 
ex:
```
apiVersion: porter.sh/v1
kind: PorterConfig
metadata:
  name: porterconfig-sample
  labels:
    porter.sh/testdata: "true"
spec:
  verbosity: debug
  defaultSecretsPlugin: kubernetes.secrets
  defaultStorage: in-cluster-mongodb
  storage:
    - name: in-cluster-mongodb
      plugin: mongodb
      config:
        url: "mongodb://mongodb.porter-operator-system.svc.cluster.local"
```

should become

```
apiVersion: porter.sh/v1
kind: PorterConfig
metadata:
  name: porterconfig-sample
  labels:
    porter.sh/testdata: "true"
spec:
  verbosity: debug
  default-secrets-plugin: kubernetes.secrets
  default-storage: in-cluster-mongodb
  storage:
    - name: in-cluster-mongodb
      plugin: mongodb
      config:
        url: "mongodb://mongodb.porter-operator-system.svc.cluster.local"
```

Update the following values in the spec:
* buildDriver -> build-driver
* defaultStorage -> default-storage
* defaultSecrets -> default-secrets
* defaultStoragePlugin -> default-storage-plugin
* defaultSecretsPlugin -> default-secrets-plugin

This will be a breaking change
