### ISSUE TITLE
Add support for telemetry in the Operator PorterConfig spec

### ISSUE THREAD

**Issue by bdegeeter** [getporter/operator#209]
Currently the PorterConfig CRD fails when a config with telemetry is loaded. 

PorterConfig:

```
apiVersion: getporter.org/v1
kind: PorterConfig
metadata:
  name: default
spec:
  namespace: demo
  verbosity: info
  default-secrets-plugin: 'kubernetes.secrets'
  default-storage: 'mongodb'
  storage:
    - name: 'mongodb'
      plugin: 'mongodb'
      config:
        url: 'mongodb://root:demopasswd@porter-operator-mongodb.demo.svc.cluster.local'
  # Send trace and log data to an Open Telemetry collector
  telemetry:
    # Enable trace collection
    enabled: true

    # Send telemetry via the grpc protocol
    # Allowed values: http/protobuf, grpc
    protocol: 'grpc'

    # The Open Telemetry collector endpoint
    endpoint: '127.0.0.1:4318'

    # Specify if the collector endpoint is secured with TLS
    insecure: true

    # Specify a certificate to connect to the collector endpoint
    #certificate: '/home/me/some-cert.pem'

    # The compression type used when communicating with the collector endpoint
    compression: 'gzip'

    # The timeout enforced when communicating with the collector endpoint
    timeout: '3s'

    # The timeout enforced when establishing a connection with the collector endpoint
    start-timeout: '100ms'

    # Used for testing that porter is emitting spans without setting up an open telemetry collector
    redirect-to-file: false

    # Additional headers to send to the open telemetry collector
    headers:
      environment: 'local'
      owner: 'porter-demo'

```

Error Message:
```
strict decoding error: unknown field "spec.telemetry"
```
**Describe the solution you'd like**
Support for a telemetry endpoint (in or out of cluster) when Porter is run via the Operator
