### ISSUE TITLE
Unable to pull image / cnab from ACR 

### ISSUE THREAD

**Issue by hemantkathuria** [getporter/operator#285]
I am trying to follow the instructions mentioned [here](https://github.com/getporter/operator/blob/main/docs/content/quickstart/_index.md): 

The below command never works and it gives the error:
```
porter credentials generate porterops -r ghcr.io/getporter/porter-operator:v1.0.0
unable to pull bundle: failed to get bundle config manifest from "ghcr.io/getporter/porter-operator:v1.0.0": bundle config not found

```
Whereas the same command works if I change the version to v0.8.2

I have pushed my porter cnab package to Azure ACR. Since it is secured, I have added a imagepull secret and added the reference of same in porter-agent service account.

```
apiVersion: v1
imagePullSecrets:
- name: crporterpocsecret
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"getporter.org/generator":"porter-operator-bundle"},"name":"porter-agent","namespace":"unifieddeployment"}}
  creationTimestamp: "2023-10-29T05:15:27Z"
  labels:
    getporter.org/generator: porter-operator-bundle
  name: porter-agent
  namespace: unifieddeployment
  resourceVersion: "453228"
  uid: 9649e9b6-54f1-4abe-aaaa-23ed3c850105

```
crporterpocsecret                              kubernetes.io/dockerconfigjson   1      5h51m

Also, I have created a custom agent config and have referred the same in my installation:

```
apiVersion: getporter.org/v1
kind: AgentConfig
metadata:
  name: customagent
spec:
  serviceAccount: porter-agent
  storageClassName: azureblob-nfs-premium
  pluginConfigFile:
    schemaVersion: 1.0.0
    plugins:
      kubernetes:
        version: v1.0.1
      azure:
        version: v1.0.1
```
In my installation, I am getting the below error continuously. Please help.

```
Creating a new installation     {"installation": "unifieddeployment/azuredep-66"}
unable to pull bundle: failed to resolve bundle manifest "crporterpoc.azurecr.io/porter-hello:v0.1.0": failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized
unable to pull bundle: failed to resolve bundle manifest "crporterpoc.azurecr.io/porter-hello:v0.1.0": failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized
```
