### ISSUE TITLE
How to support invoke through the operator?

### ISSUE THREAD

**Issue by carolynvs** [getporter/operator#39]
The new model for the operator is based around calling the porter apply commands that are being introduced in v1. This allow us to support the following options:

* install when a CRD is added
* upgrade when a CRD is changed
* uninstall when a CRD is deleted

Since the new model does not support imperative commands, the questions I have are:

* Do we need to? Is calling one off commands on an installation something that we need to support? Or like the Helm operator, should we just stick to the installation lifecycle, and otherwise people should continue to use the porter cli for one-offs?
* If we did support it, what would that look like? One thought would be to have a Run CRD that models executing any arbitrary porter command.

For our first iteration of the operator, @squillace has encouraged us to consider this out of scope but I wanted to get the discussion out there so others can provide feedback.

**Comment by squillace** [comment]
the high order bit is to hit the spec ops, which is the same thing as k8s does in any case for it's server api. But I **do** think that operators ought to support custom actions for arbitrary events. kubectl has diff, and I would expect porter to be able to support operations like that or others that have to do with operations for a bundle. It's an "operator" after all. 

How that should be done is definitely the question...

**Comment by carolynvs** [comment]
Something to chew on

**Comment by carolynvs** [comment]
now that the installation controller has been rewritten, I think it solves this problem a bit. It has a super generic portion in the controller where I can run any arbitrary porter command, passing in a set of env vars, and files.

If I split it out into a separate controller with its own CRD, people could run any command they need.

**Comment by carolynvs** [comment]
@bdegeeter Here's a rough draft of what the custom resource for defining a command that the operator should run with the porter agent. I'm going to keep working on splitting out the installation controller in two but this is what I'm thinking the new controller will use for a resource.

Essentially we want to support a subset of fields that are available on the pod spec that are relevant to the agent. Anything that configures the agent further, such as image secrets, retry policy, resource usage, etc should be added to the AgentConfig resource (those are examples of things that we don't support now but may in the future).

```yaml
apiVersion: porter.sh/v1
kind: AgentAction
metadata:
  # I expect most people won't pick an exact name and will let the action make a unique one
  generateName: mybun-backupdb
  annotations:
    # Set the retry annotation to a new value to rerun the agent
    porter.sh/retry: "random string"
  labels:
    # Any labels set here are applied to the resulting jobs, secret, and volume
    porter.sh/resourceKind: Installation
spec:
  agentConfig: customAgentConfigRef
  porterConfig: customPorterConfigRef
  command: /app/.porter/agent # this is the default entrypoint but we can allow people to override it
  arguments:
    - invoke
    - --action=backupdb
    - --cred=mycreds
  env:
    - name: PORTER_FLAG
      value: true
  envFrom:
    - configMapRef:
        name: special-config
  volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: special-config
```
