### ISSUE TITLE
Accessing porter data from inside the cluster

### ISSUE THREAD

**Issue by carolynvs** [getporter/operator#42]
bdegeeter asked in Slack if there was a way to get outputs from running a bundle, after the installation is completed back into the cluster.

> The workflow I’m supporting is something like this…
> * azure service bus event outside k8s creates porter.sh/Installation
> * the k8s events for the initial job created are watched for a success or failure
> * upon success/failure the status of the job is published back to the az service bus with the outputs of the bundle in the message if successful

Maybe we could add something to the Installation spec that lets you grab data after the installation is updated, and stash it in k8s.

```
kind: Installation
spec:
  installationName: wordpress
  # ...
  outputs:
    - name: endpoint # put just the endpoint output into the secret key
       kind: secret
       name: mywordpress
       key: endpoint
```

```
kind: Installation
spec:
  installationName: wordpress
  # ...
  outputs: # put all outputs into the configmap
    - kind: configmap
       name: mywordpress
```
