### ISSUE TITLE
Support uninstall without removing the CRD

### ISSUE THREAD

**Issue by carolynvs** [getporter/operator#46]
In the Porter community meeting today, it came up that some people will want to use Kubernetes as the way to tell what is installed, and also _what used to be installed_. Right now the design is to uninstall when the CRD is deleted. To support this other way of managing resources, we could add a field to the installation indicating if it's installed or not.

**existing installation**
```yaml
kind: Installation
metadata:
  name: mywordpress
spec:
  name: wordpress
  bundle:
    repository: getporter/wordpress
    version: 0.4.0
status:
  installedOn: 2021-10-01... # Timestamp of when the bundle was installed
```

**installation that has been uninstalled**
```yaml
kind: Installation
metadata:
  name: mywordpress
spec:
  uninstalled: true # Add this to the spec to uninstall
  name: wordpress
  bundle:
    repository: getporter/wordpress
    version: 0.4.0
status:
  installedOn: 2021-10-01
  uninstalledOn: 2021-10-10... # Timestamp of when it was uninstalled
```
