### ISSUE TITLE
Expose bundle outputs inside a cluster

### ISSUE THREAD

**Issue by carolynvs** [getporter/operator#63]
The outputs generated from running an installation should be natively accessible from Kubernetes. So after the installation completes the output values should be copied into a secret.

We have a couple options for output syncing:

1. Create a new secret for the outputs after each run. This more faithfully represents how porter works (outputs are immutable and tied to a porter run), but puts more decisions on the consumer. Such as do they want the most recent value of an output, or do they want the output generated by a specific generation of the installation.
2. Keep a single secret per installation and update it with the outputs after each run. This would be easier for people to consume but perhaps oversimplifies things.

I have added https://github.com/getporter/porter/issues/1877 to porter so that we can correlate an installation spec generation with a particular run (and its outputs).

**Comment by bdegeeter** [comment]
Based on our last dev meeting here's some high level ideas regarding outputs.  Just wanted
to get enough ideas out to go a bit deeper into the design.

* Annotation to enable
  * **porter.sh/enable-outputs: "true"**
  ```
  apiVersion: porter.sh/v1
  kind: Installation
  metadata:
    name: test-me
    namespace: quickstart
    annotations:
      # enable creation of InstallationOutput resource
      porter.sh/enable-outputs: "true"
  spec:
    schemaVersion: 1.0.0
    namespace: quickstart
    name: test-me
    bundle:
      repository: ghcr.io/bdegeeter/porter-test-me
      version: 0.3.0
    parameters:
      name: quickstart
  ```

* InstallationOutput CRD
  ```
  apiVersion: porter.sh/v1
  kind: InstallationOutput
  metadata:
    name: test-me # use the same name as the installation resource
    namespace: quickstart
    generation: 1
    labels:
      porter.sh/managed: "true"
      porter.sh/resourceGeneration: "1"
      porter.sh/resourceKind: Installation
      porter.sh/resourceName: test-me
    ownerReferences:
    - apiVersion: porter.sh/v1
      blockOwnerDeletion: true
      controller: true
      kind: Installation
      name: test-me
  spec:
    namespace: quickstart
    name: test-me
  status:
    # Should we use phase to show output is 
    # associated with an Installation in transition?
    phase: (Scheduled|Started|Completed|Succeeded)
    # all outputs from bundle
    outputs:
    - name: outAction
      type: string
      sensitive: false
      value: install
    - name: outDelay
      type: integer
      sensitive: false
      value: 1
    - name: outExitStatus
      type: integer
      sensitive: false
      value: install
    - name: outInsecureValue
      type: string
      sensitive: true
      key: plugin-secret-key-name
  ```

  * Notes
    * Outputs as status (taken directly from porter installation outputs show schema)
    * InstallationOutput as new resource for isolated RBAC
    * carry forward labels where appropriate
    * what are the limits of storing values in status?

  * Behaviors
    * Uses porter v1.0.0-alpha.20 behavior for outputs
      * If bundle does not mark output as sensitive (default) provide the value
      * If bundle marks output as sensitive provide the secret key
    * The InstallationOutput resource is created when Installation 
      state Completed is discovered but before it is set.
      * goal is to guarantee output resource available when Installation complete
    * Should controller remove (or invalidate) existing InstallationOutputs? when?
      * Installation uninstall via resource attribute
        * remove or invalidate at the start of uninstall (with delete of InstallationOutput at end?)
      * Installation resource delete
        * remove or invalidate at the start of uninstall (with delete of InstallationOutput at end?)
      * Installation resource update for upgrade
        * remove or invalidate at the start of update (with update of resource at the end?)
      * Can a spec field or status be used to show an InstallationOutput is in transition
        because of an upgrade or uninstall?
