### ISSUE TITLE
Define required plugins on the agent config

### ISSUE THREAD

**Issue by carolynvs** [getporter/operator#77]
We need a way to say which plugins are installed on the porter agent. Here's one way to make that work:

1. Create an AgentConfig and define which plugins you require:
    ```yaml
    kind: AgentConfig
    spec:
      plugins:
        - name: kubernetes
           feedUrl: https://cdn.porter.sh/plugins/atom.xml
           version: v1.2.3
    ````
2. The (new) AgentConfig controller sees the new AgentConfig
    * Looks for an existing PVC named using a hash of the plugin metadata. For example it would hash the plugin name + source + version and use that hash as the PVC name.
    * Creates a temporary PVC if it doesn't exist. Annotating it with the plugins used to create it.
    * Creates an AgentAction that mounts that PVC and runs `porter plugins install` for all the defined plugins
    * When the action completes, the AgentConfig controller, deletes the PVC with the temp name and make the final PVC named using the hash of the plugin metadata.
3. When the AgentAction controller creates the PorterAgent job, it uses the new plugins list on the agent action to generate that same hash, and mount that PVC. (We do the temp PVC name trick to ensure the volume is initialized before the pod runs, k8s will wait to schedule it until the PVC exists).
4. May need to tweak the agent to copy the contents from the mounted plugins PVC into $PORTER_HOME/plugins. I'm hoping we can use subPath to workaround this (https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath)
